### PR TITLE
Add flags to disable riding & leashing

### PR DESCRIPTION
**Pull request by phemmer**
Resubmit of #35 since github decided to close it and won't let me re-open.

This adds 2 flags:

disableLeash - This prevents players from using a lead on pets owned by others.
disableRiding - This prevents players from riding horses & donkeys owned by others.
Also including a fix for the vault maven group ID, as the old one no longer exists.

### CODE REVIEW

**Comment by phemmer** [comment]
Made the change locally, but haven't had a chance to test yet.

I also think I see an issue where if a user tries to give or release a horse they don't own, the hook sends the "You do not own this pet!" message and returns without cancelling the event, allowing the user to mount it. I just need to move the horse handling code up above that and it should be addressed.

**Comment by PyvesB** [comment]
@phemmer I would like to do a release with Minecraft 1.16 support. Shall I wait a little longer for your contribution to be landed as well? :)

**Comment by phemmer** [comment]
Ill get to back to it in the next hour or two. Sorry for delay. Just wrapped up in another plugin. But this is simple enough i should be able to take care of it fast.

On July 4, 2020 6:24:41 AM EDT, "Pierre-Yves B." <notifications@github.com> wrote:
>@phemmer I would like to do a release with Minecraft 1.16 support.
>Shall I wait a little longer for your contribution to be landed as
>well? :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PyvesB/PetMaster/pull/36#issuecomment-653748629

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by phemmer** [comment]
Ok. Tested changes and they appear good. Code is pushed.

**Comment by PyvesB** [comment]
I just noticed post-merge that `version` was an unused field in _PlayerLeashListener_, not to worry, I'll delete it!

**Pull request merged**
