### PR TITLE
add Turkish (TR) translations

### PR DESCRIPTION
**Pull request by NotAShelf**
Alright to be honest, I am not native to the Turkish language nor I am a renowned speaker of it. However, I am quite confident in my ability to translate to or from said language so I believe I have made a decent job at those translations.

Due to the nature of the Turkish language and how sentences are structured, or how some expressions work with context; the translation may appear wonky to Turkish speakers. I am really sorry if I have made some inaccurate translations,  but again, I don't expect any inaccuracies.

With that said, this completes my translation after ~~2~~ now three revisions and multiple attempts to translate as good as possible.
Any native speakers, I am looking forward to collaborate on this translation (if necessary) and I would appreciate any improvements.

P.S for the author: I don't know how much you would like to receive code from a non-expert Java user, and considering that it is a mere fork with some improvements I would understand if you don't want to merge; but I would like to open a second pull request today merging some code from [this plugin (fork)](https://github.com/NotAShelf/pet-teleport) since I believe it could be useful to have said feature in this plugin, seeing how they are related and all.

### CODE REVIEW

**Comment by PyvesB** [comment]
Thanks for the Turkish translation! 🎉 

> but I would like to open a second pull request today merging some code from [this plugin (fork)](https://github.com/NotAShelf/pet-teleport) since I believe it could be useful to have said feature in this plugin, seeing how they are related and all.

Could you please expand on which precise features you would like to merge back into PetMaster?

**Comment by NotAShelf** [comment]
petTeleport is a simple plugin, it simply prevents your pets from getting stuck in unloaded chunks, everything it does is practically in [UnloadListener.java](https://github.com/NotAShelf/pet-teleport/blob/master/src/main/java/com/raus/petTeleport/UnloadListener.java)

**Comment by NotAShelf** [comment]
of course I'm not going to merge the entire plugin, I will simply attempt to tamper the main feature of the plugin; pets teleport to you & not get stuck in unloaded chunks as you move

**Comment by PyvesB** [comment]
Sounds like a good idea. You would also need to add a configuration option, a permission and hook things into the enabled/disabled functionality of PetMaster. 😉

**Review by PyvesB — APPROVED** [review]

**Comment by NotAShelf** [comment]
would love to do that, but unfortunately I have no clue how to work with those haha
I'll try though

**Pull request merged**
